In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
KSE100 = pd.read_csv('KSE100.csv')

In [3]:
f = open("closing11-9Oct.lis", "r")

In [4]:
import csv
with open('9Oct.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    for line in f:
        i = 0
        Date = ''
        Ticker = ''
        x=''
        y=''
        Open = ''
        High = ''
        Low = ''
        Close = ''
        Volume = ''
        while line[i]!='|':
            Date+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            Ticker+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            x+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            y+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            Open+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            High+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            Low+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            Close+=line[i]
            i+=1
        i+=1
    
        while line[i]!='|':
            Volume+=line[i]
            i+=1
        i+=1
    
        writer.writerow([Date, Ticker, x, y, Open, High, Low, Close, Volume])

In [5]:
df = pd.read_csv('9Oct.csv', 
                  names=["Date", "Ticker", "x", "y","Open", "High","Low","Close","Volume"]
                  ,index_col=False)
df = df.drop(['x', 'y'], axis = 1)
df.head(10)

        Date Ticker   Open   High    Low  Close  Volume
0  09OCT2020   HGFA   9.43   9.43   9.43   9.43    1000
1  09OCT2020   HIFA   3.31   3.50   3.12   3.50    4500
2  09OCT2020  SINDM   9.70   9.70   8.75   8.86   28500
3  09OCT2020   TSMF   3.71   4.80   3.70   3.75   35500
4  09OCT2020    ARM  10.70  12.25  10.70  12.25    1000
5  09OCT2020   FECM   2.49   2.70   2.03   2.66  111500
6  09OCT2020   FFLM   0.00   3.70   3.70   3.90    5000
7  09OCT2020  ORIXM  21.00  21.30  21.00  21.29   71500
8  09OCT2020   FHAM  11.50  11.60  11.50  11.56   88000
9  09OCT2020   FTMM  14.50  14.50  14.50  14.50     500

In [6]:
filtered = KSE100['Ticker'].tolist() #Filtered companies stored in a list

names = df['Ticker'].tolist()
for i in range(len(df)-1):
    name = str(names[i]) + " PA Equity"
    #print(name)
    if name in filtered: #Extracts only shortlisted companies
        #df = new_data #Extract all rows under those 7 columns
        df['Open'] = pd.to_numeric(df['Open']) #Change datatype of Open (Initially object type)
        df['High'] = pd.to_numeric(df['High']) #Change datatype of High (Initially object type)
        df['Low'] = pd.to_numeric(df['Low']) #Change datatype of Low (Initially object type)
        df['Close'] = pd.to_numeric(df['Close']) #Change datatype of Close (Initially object type)
        df['Volume'] = pd.to_numeric(df['Volume']) #Change datatype of Volume (Initially object type)
        df['Date'] = pd.to_datetime(df['Date']) #Change data type to datetime (Iitially object type)
        #df = df.drop(['Ticker'], axis = 1)
        df.iloc[i:i+1].to_csv(path_or_buf = 'D:/Habib/Kaavish/Deep-PSX-Kaavish/9Oct/' + name + '.csv', encoding='utf-8',  sep = ',', index = False) #Save dataframe as CSV